app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_pagedown import PageDown
from config import config


bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
pagedown = PageDown()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    pagedown.init_app(app)
    #
    # if not app.debug and not app.testing and not app.config['SSL_DISABLE']:
    #     from flask_sslify import SSLify
    #     sslify = SSLify(app)

    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)


    return app

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import render_template

from app.core import run
from app.home import home


@home.route('/', methods=['GET'])
def index():
    return render_template('index.html')



@home.route('/selenium', methods=['GET'])
def selenium():
    return render_template('selenium.html')



@home.route('/baidu_search', methods=['GET'])
def baidu_search():
    filename = run.run()
    return render_template("result/" + filename)

app/templates/footer.html
<footer style="background: rgba(0,0,1,1);" class="footer navbar-fixed-bottom">
        <div class="wrap-footer">
            <div class="container">
                <div class="row">
                    <div class="col-footer col-md-3">
                        <h2 class="footer-title">关于我们</h2>
                </div>
            </div>
        </div>
        <div class="bottom-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <p>Copyright &copy; 2017 jacklibra All rights reserved.</p>
                        <p>技术支持jacklibra提供.</p>

                    </div>
                    <div class="col-md-4">

                    </div>
                    <div class="col-md-4">
                        <ul class="list-inline quicklinks">
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        </div>
</footer>

{% block script%}
<script>
    $(function(){
       $('.navbar-nav li').on('click',function(){
           $(this).addClass("active").siblings().removeClass("active");
       });
       $('.navbar-brand').on('click',function(){
           $(this).addClass("active");
           $('.navbar-nav li').removeClass("active");
       });
//       $('.dropdown-menu li').on('click',function(){
//           $(this).addClass("active").siblings().removeClass("active");
//       });
    });
</script>
{% endblock %}

app/templates/header.html
{% extends "bootstrap/base.html" %}

{% block title %}自动化测试{% endblock %}

{% block navbar %}
<nav class="navbar navbar-inverse" role="navigation" style="background: rgba(0,0,0,0.8);">
    <div class="container-fluid">
    <!--<div class="navbar-header">-->
    <!--</div>-->
    <div>
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="javascript:;">首页</a></li>
            <li class="active"><a href="#">功能测试</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    自动化测试
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{{ url_for('home.selenium') }}">selenium</a></li>
                    <li class="divider"></li>
                    <li><a href="">持续集成</a></li>
                </ul>
            </li>
            <li class=""><a href="javascript:;">性能测试</a></li>
        </ul>
    </div>
    </div>
</nav>
{% endblock %}

app/templates/index.html
{% include 'header.html' %}



{% block content %}
<div class="container" >
<div class="panel panel-default">
    <div class="panel-heading">职业介绍</div>
    <div class="panel-body">
        <p>测试工程师，软件质量的把关者，工作起点高，发展空间大。我国的软件测试职业还处于一个发展的阶段，所以测试工程师具有较大发展前景。
目前传统的软件行业还是以软件测试工程师为主，但是在新兴的互联网行业大多还是以QA来命名这个职位，也就是质量保证。
        </p>
    </div>
    <ul class="list-group">
        <li class="list-group-item">Software Development Engineer in Test</li>
        <li class="list-group-item">Software Development Engineer in Test</li>
        <li class="list-group-item">Software Development Engineer in Test</li>
        <li class="list-group-item">Software Development Engineer in Test</li>
    </ul>
    <div class="panel-heading">历史发展</div>
    <div class="panel-body">
    <p>计算机软件产品检验员(即软件测试工程师)早在2005年就被劳动和社会保障部门列入第四批新职业中。经过短短几年的发展，软件测试员已跻身IT业抢手人才之列。究其原因主要有二。　首先是企业对测试“经济价值”的认可。
有调查显示，通过必要测试，软件缺陷可减少75%，而软件的投资回报率则可增长到350%。对于一个软件企业来说，只有它的产品或是项目质量完全地得到认可，业务才有可能进一步扩展。很多中大型软件企业设立了单独的测试部，与开发部并行运作，测试人员也与开发人员平起平坐。
除了产业的自身需求外，国家政策的大力扶植也是软件测试大力发展的原因。2007年，信产部联合五部委颁布124号文件，特别强调要“加快培养软件测试人才，开展软件评测技术的研究”。为了配合2008年奥运会的召开，国家科技部门、北京市政府主管部门和北京奥组委等投入近20亿，组建10个重大的智能型项目，涉及上百个软件系统。如此庞大的信息服务系统，对软件测试人员的需求更是剧增，也将进一步扩大人才缺口。 </p>
    </div>
    <div class="panel-heading">职业待遇</div>
    <div class="panel-body">
    <p>软件质量的把关者，人才凤毛麟角，薪酬上升空间非常大。
质量是企业的生命线，测试工程师作为软件质量的把关者，因为职位的重要而有较高的待遇就顺理成章了。另外，“物以稀为贵” 的市场规律也使得当前极为紧俏的测试工程师“钱景看好”。
并且我国的软件测试职业还处于一个发展的阶段，随着软件行业对产品质量重视程度的提高，受过系统培训、掌握先进测试技术的软件测试从业人员的薪酬上升空间大。从企业人才需求和薪金水平来看，软件测试工程师的年工资还有逐年上升的明显趋势。 </p>
    </div>
    <div class="panel-heading">职业前景</div>
    <div class="panel-body">
    <p>在外界环境大好的情况下，软件测试却面临着自身的严峻考验——人才紧缺。在国外，一般软件测试人员与软件开发人员的岗位设置比例是1：1，像微软在开发windows2000时测试开发人员比例高到1.7：1，由此可见软件测试岗位重要性的一般。据前程无忧调查显示，国内120多万软件从业者中，真正能担当测试职位的不足5万，人才缺口已超20万，并随需求逐年增长。
软件测试人才需求量的加大，除了受产业先行的波及外，主要是受教育滞后的影响。由于及时捕捉到市场的需求，部分IT职业培训机构率先驶入测试培养的蓝海，紧跟发展趋势，开设了一系列科学完善的课程体系，为软件企业培养了众多专业软件测试工程师，成为人才培养的主力军。企业可通过内部培训、引进人才等方式来培育人才，但受人力成本的限制，这些方式没有大规模普及。另外，国内部分高等院校也开始着手准备，召开软件测试教学研讨会，筹划专业开设的相关事宜 </p>
    </div>
    <div style="width:100%;height:123px;">

    </div>
</div>
</div>



{% include 'footer.html' %}
{% endblock %}

app/templates/selenium.html
{% include 'header.html' %}


{% block content %}
<div class="container" >
<div class="panel panel-default">
    <div class="panel-heading">selenium介绍</div>
    <div class="panel-body">
        <p>Selenium也是一个用于Web应用程序测试的工具。Selenium测试直接运行在浏览器中，就像真正的用户在操作一样。支持的浏览器包括IE、Mozilla Firefox、Mozilla Suite等。这个工具的主要功能包括：测试与浏览器的兼容性——测试你的应用程序看是否能够很好得工作在不同浏览器和操作系统之上。测试系统功能——创建衰退测试检验软件功能和用户需求。支持自动录制动作和自动生成。Net、Java、Perl等不同语言的测试脚本。Selenium 是ThoughtWorks专门为Web应用程序编写的一个验收测试工具。</p>
    </div>
     <ul class="list-group">
         <li class="list-group-item"><a href="{{ url_for('home.baidu_search') }}">百度搜索测试</a></li>
        <!--<li class="list-group-item">Software Development Engineer in Test</li>-->
        <!--<li class="list-group-item">Software Development Engineer in Test</li>-->
        <!--<li class="list-group-item">Software Development Engineer in Test</li>-->
    </ul>
    <div style="width:100%;height:123px;"></div>
</div>
</div>

{% include 'footer.html' %}

{% endblock %}